transport_type_dict = {
    'ASC':'Aufzug',
    'B':'Bus',
    'BN':'Nachtbus',
    'BP':'PanoramaBus',
    'BUS':'Bus',
    'CAR':'Fernbus national',
    'CAX':'Fernbus international',
    'EB':'Eilbus',
    'EXB':'Expressbus',
    'ICB':'InterCity-Bus',
    'KB':'Kleinbus',
    'NB':'Nacht-Bus',
    'NFB':'Niederflur-Bus',
    'NFO':'Niederflur-Trolleybus',
    'RUB':'Rufbus',
    'TX':'Taxi',
    'SL':'Sesselbahn',
    'CC':'Zahnradbahn',
    'GB':'Gondelbahn',
    'LB':'Luftseilbahn',
    'PB':'Pendelbahn',
    'M':'Metro',
    'FUN':'Standseilbahn',
    'BAT':'Schiff',
    'BAV':'Dampfschiff',
    'FAE':'F„hre',
    'KAT':'Katamaran',
    'NFT':'Niederflur-Tram',
    'T':'Tram',
    'TN':'Nachttram',
    'AIR':'Flugzeug',
    'UUU':'Unbekannte Art',
    'AG':'Agenturzug',
    'ARC':'Arco',
    'ARZ':'Autoreisezug',
    'AT':'Autotunnelzug',
    'ATR':'Altaria',
    'ATZ':'Autotunnelzug',
    'AVE':'Alta Velocidad ES',
    'BEX':'Bernina Express',
    'CAT':'City Airport Train',
    'CNL':'CityNightLine',
    'D':'Schnellzug',
    'E':'Eilzug',
    'EC':'EuroCity',
    'EM':'Euromed',
    'EN':'EuroNight',
    'ES':'Eurostar Italia',
    'EST':'Eurostar',
    'EXT':'Extrazug',
    'GEX':'Glacier Express',
    'IC':'InterCity',
    'ICE':'InterCityExpress',
    'ICN':'IC-Neigezug',
    'IN':'InterCityNacht',
    'IR':'InterRegio',
    'IRE':'Interregio-Express',
    'IT':'Italo',
    'JAT':'Gef„ngniszug',
    'MAT':'LeermaterialZ (Reisezugswagen)',
    'MP':'LeermaterialZ Personenbef”rd',
    'NJ':'nightjet',
    'NZ':'Nacht-Zug',
    'P':'Zug ohne Gew„hr',
    'PE':'PanoramaExpress',
    'R':'Regio',
    'RB':'Regionalbahn',
    'RE':'RegioExpress',
    'RJ':'Railjet',
    'RJX':'railjet xpress',
    'S':'S-Bahn',
    'SN':'Nacht-S-Bahn',
    'STB':'Stadtbahn',
    'TAL':'Talgo',
    'TER':'Train Express Regional',
    'TE2':'TER200',
    'TGV':'Train … grande vit.',
    'THA':'Thalys',
    'TLK':'Twoje Linie Kolejowe',
    'UEX':'UrlaubsExpress',
    'VAE':'Voralpen-Express',
    'WB':'Westbahn',
    'X':'InterConnex',
    'X2':'X2000 Neigezug',
    'ZUG':'Zugskategorie unbekannt',
    'walk': 'walk'
}
